#!/usr/bin/env python3

import sys
import asyncio
from cm99109 import Machine
import intelhex

ih = intelhex.IntelHex(sys.argv[1])
ih.dump(sys.stdout)

machine = Machine()

for start, end in ih.segments():
    segment = [ih[i] for i in range(start, end)]
    machine.load(segment, start)

async def run():

    loop = asyncio.get_event_loop()
    loop.create_task(machine.execute())

    await machine.reset()

    while True:
        await asyncio.sleep(1)


loop = asyncio.get_event_loop()
loop.run_until_complete(run())

