#!/usr/bin/env python3

from cm99109 import Programmer
import asyncio

# Main code, just run the programmer websocket
loop = asyncio.get_event_loop()
a = Programmer()
loop.run_until_complete(a.run())
