#!/usr/bin/env python3

import sys
import intelhex
from cm99109 import Parser

with open(sys.argv[1]) as f:
    data = f.read()
    tree = Parser.parse(data)
    tree = Parser.resolve(tree)

mc = []
for label, instr in tree:

    if instr != None:
        c = instr.to_code()
        mc.extend(c)

ih = intelhex.IntelHex()
ih[0:len(mc)] = mc
ih.write_hex_file(sys.stdout)

